version: "3"
services:
  db:
    image: postgres:13.3-alpine
    container_name: sdc-db
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  web-server:
    container_name: sdc-server
    env_file:
      - web_vars.env
    build: .
    depends_on:
      - "db"
    ports:
      - "2222:2222"
    extra_hosts:
      host.docker.internal: host-gateway
volumes:
  db-data: